# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Install nicescad
RUN pip install nicescad

# Make port 80 available to the world outside this container
EXPOSE 80

# Run p2scad when the container launches
CMD ["p2scad", "--serve", "--host", "0.0.0.0", "--port","80"]
