#!/bin/bash

# This script was created to resolve https://github.com/WolfgangFahl/nicescad/issues/28
# Author: ChatGPT-4 by OpenAI
# Date: 30th July, 2023

function usage {
    echo "Usage: $0 start|stop|restart|rebuild [OPTIONS]"
    echo "   start|stop|restart|rebuild: Start, stop, restart, or rebuild and start the services"
    echo "   OPTIONS:"
    echo "     --nicescad-port : Port for the nicescad service (default 9858)"
    echo "     --p2scad-port   : Port for the p2scad service (default 8093)"
}

function start_services {
    # Start the services using Docker Compose
    docker-compose up -d
}

function stop_services {
    docker-compose down
}

function rebuild_services {
    # Rebuild the Docker images
    docker-compose build --no-cache
    start_services
}

# Default port values
NICESCAD_PORT=9858
P2SCAD_PORT=8093

# Command line option parsing
if [ $# -lt 1 ]
then
  usage
  exit 1
else
  ACTION=$1
  shift
  while [ "$1" != "" ]
  do
    case $1 in
      --nicescad-port )  shift
                          NICESCAD_PORT=$1
                          ;;
      --p2scad-port )    shift
                          P2SCAD_PORT=$1
                          ;;
      --help )           usage
                          exit
                          ;;
      * )                usage
                          exit 1
    esac
    shift
  done
fi

# Create docker-compose.yml file
cat << EOF > docker-compose.yml
version: '3.8'
services:
  nicescad:
    image: nicescad-service
    build:
      context: .
      dockerfile: Dockerfile.nicescad
    ports:
      - ${NICESCAD_PORT}:9858
  p2scad:
    image: p2scad-service
    build:
      context: .
      dockerfile: Dockerfile.p2scad
    ports:
      - ${P2SCAD_PORT}:80
EOF

# Perform the requested action
case $ACTION in
  start )   start_services
            ;;
  stop )    stop_services
            ;;
  restart ) stop_services
            start_services
            ;;
  rebuild ) rebuild_services
            ;;
  * )       usage
            exit 1
esac
